services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5162:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./backend/Data:/app/Data

  frontend:
    build: ./league-tac-toe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8080
